name: Makefile CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm' # ускоряет повторные сборки

    - name: setup
      run: make setup

    - name: test
      run: make test

    - name: lint
      run: make lint

    - name: Print Hello from Hexlet
      uses: hexlet-components/hello-from-hexlet-action@release
