name: Makefile CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4

    - name: use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: setup
      run: make setup

    - name: test
      run: make test

    - name: lint
      run: make lint

    - name: Print Hello from Hexlet
      uses: hexlet-components/hello-from-hexlet-action@release
